baseURL = "http://example.org/"
languageCode = "en-us"
title = "Diego Rojas Site"
theme = "nix"
[params]
  GithubID = "https://github.com/dicrojasch"
  LinkedInID = "https://www.linkedin.com/in/diego-rojas-6b849a39/"
  GoogleplusID = "https://plus.google.com/u/1/108696919393100046172"
  FacebookID = "https://www.facebook.com/diego.rojas.37266136"
  Name = "Diego Rojas"
  Email = "dicrojasch@unal.edu.co"
  About = "Systems an computing engineering student"
  ProfilePicture = "https://www.wps.com/images/wps4linux/linux.png"
